### ISSUE TITLE
API to stop bot

### ISSUE THREAD

**Issue by arunthampi** [zerobotlabs/relax#16]

**Comment by ericktai** [comment]
👍

**Comment by arunthampi** [comment]
@ericktai coming soon! ⌛

**Comment by arunthampi** [comment]
Closed by https://github.com/zerobotlabs/relax/commit/9cba92d5029a4b0414af2308e3b78223710586e5 & corresponding API in relax-rb: https://github.com/zerobotlabs/relax-rb/commit/ad4c08d58fb7fd6367772bb0cef3ac0fb091915e (available in 0.5.0 in rubygems)
