### ISSUE TITLE
It is not clear how to scale this

### ISSUE THREAD

**Issue by thelinuxlich** [zerobotlabs/relax#18]
Just spawn Relax processes and all is good? No duplication?
Also, I don't see the event for new messages and how am I supposed to make the bot answer people?

**Comment by arunthampi** [comment]
> Just spawn Relax processes and all is good? No duplication?

Yup can spawn more processes, exactly no duplication of messages.

> Also, I don't see the event for new messages and how am I supposed to make the bot answer people?

You should look for the `message_new` event: https://github.com/zerobotlabs/relax#text . If you are using Ruby, you can check out the Ruby client: https://github.com/zerobotlabs/relax-rb and an example Rails app: https://github.com/zerobotlabs/relax_on_rails

**Comment by thelinuxlich** [comment]
What made you use Redis? I can see this working with NSQ

**Comment by arunthampi** [comment]
ah haven't explored NSQ, but with Redis, I store both state (as a key-value store) as well as use it as a message queue so it was win-win in terms of using a single dependency for both needs. Also familiarity with using it was one reason. Open to looking at NSQ as a backend.

**Comment by thelinuxlich** [comment]
Oh I forgot you need to maintain state, then Redis is preferable.

By the way, does it support Redis Cluster?

**Comment by arunthampi** [comment]
@thelinuxlich haven't tried with redis cluster yet.

**Comment by thelinuxlich** [comment]
Your redis driver already supports it: https://godoc.org/gopkg.in/redis.v3#NewClusterClient
