### ISSUE TITLE
Handle "migration_in_progress" error generated by Slack

### ISSUE THREAD

**Issue by arunthampi** [zerobotlabs/relax#20]
Seems to be generated by https://api.slack.com/events/team_migration_started

**Comment by arunthampi** [comment]
reported by @jmanian

**Comment by arunthampi** [comment]
Fix available in https://github.com/zerobotlabs/relax/pull/21 @jmanian, have deployed this to my relax installs, will be great if you can deploy and see if it helps remove this log (it should now retry connecting if error is `migration_in_progress`)

**Comment by jmanian** [comment]
Great, I will deploy it. We got a small flood of EOF errors over each of the past two weekends. Combine that fact with the `migration_in_process` errors and I'm guessing that Slack has been doing some maintenance over the past two weekends. So maybe we'll see some more EOF errors this coming weekend and we'll get to see if this works.

**Comment by jmanian** [comment]
And with the weekend comes more websocket errors — definitely some kind of migration or maintenance happening on Slack's end.

This time I got a combination of EOF errors and this new one:
```
msg="error reading message from slack websocket connection" error="read tcp xyz.xyx.xyz.xyz:abcde->abc.abc.abc.abc:abc: use of closed network connection"
```
In all cases it automatically restarted 👍

**Comment by arunthampi** [comment]
sweet :+1:

**Comment by arunthampi** [comment]
closed by https://github.com/zerobotlabs/relax/pull/21
