### ISSUE TITLE
Ignore message_new event 

### ISSUE THREAD

**Issue by robguilfoyle** [zerobotlabs/relax#24]
I'm seeing some bots ignoring messages making the user send the message again. It appears the hset to redis returns a 0 but the message definitely has not been set before as there is only one dyno:

`boolCmd := tx.HSetNX(os.Getenv("RELAX_MUTEX_KEY"), key, "ok")`

Any thoughts around this?

**Comment by robguilfoyle** [comment]
@arunthampi Just putting this on top of your inbox. Thanks for your work on this project btw.

**Comment by arunthampi** [comment]
@robguilfoyle thanks for reporting this, haven't seen this error yet -- let me investigate further and get back to you

**Comment by robguilfoyle** [comment]
We identified it as an issue with redis connections getting stale and being timed out. I'll through up a PR once done.

**Comment by arunthampi** [comment]
@robguilfoyle awesome, i have an external script that cleans up stable redis connections, curious to see how you guys have solved it!

**Comment by arunthampi** [comment]
Closing this for now.
