### ISSUE TITLE
Notes & questions from newcomer (building & scaling)

### ISSUE THREAD

**Issue by thbar** [zerobotlabs/relax#29]
Thanks for your work on relax! I'm just trying it out now. I have 2 questions + 1 note for now :smile:

1/ I'm only a casual go developer, and I wasn't completely sure what was the right way to setup $GOPATH and using Godeps ; it would be great to have a little README note to show how to reproduce the exact same build (but I managed to get some build at least without too much pain).

2/ I wonder : how many concurrent connections are supposed to be handled by a single relax process? Are we more in the hundreds, or thousands, or more? (I'll do my test but since you are using relax in production, a bit of feedback would be great !)

3/ I went through `InitClients` and my understanding is that if you start 2 processes, the 2 processes will both start a RTM connection. If I want to use relax for horizontal scalability here, wouldn't it be better to shard the connections per process? (well this obviously depends of the answer to question 2!)

Thanks again for your work and replies, in advance @arunthampi!

**Comment by arunthampi** [comment]
Great questions @thbar, please see inline:

> 1/ I'm only a casual go developer, and I wasn't completely sure what was the right way to setup $GOPATH and using Godeps ; it would be great to have a little README note to show how to reproduce the exact same build (but I managed to get some build at least without too much pain).

Sure, with Relax: Go knowledge is not required, you can download binaries here: https://dl.equinox.io/zerobotlabs/relax/stable

> 2/ I wonder : how many concurrent connections are supposed to be handled by a single relax process? Are we more in the hundreds, or thousands, or more? (I'll do my test but since you are using relax in production, a bit of feedback would be great !)

We've successfully run 2000 Slack teams on single Heroku standard dyno (512MB) with room to spare!

> 3/ I went through InitClients and my understanding is that if you start 2 processes, the 2 processes will both start a RTM connection. If I want to use relax for horizontal scalability here, wouldn't it be better to shard the connections per process? (well this obviously depends of the answer to question 2!)

Yes right now there is no "sharding" of connections, but that's something that I'd love to add without adding complexity, would love to hear your thoughts on how we can achieve that.

**Comment by thbar** [comment]
Great answers @arunthampi - thanks! Here are my answers :

1/ I was aware of that, yet I preferred to make sure I was able to build from source in reliable fashion :-)

2/ this is great, and appears to be a lower memory footprint than what I've seen with node/ruby counterparts (which isn't surprising)

3/ thanks to 2/, sharding won't be necessary too soon. That said a couple of thoughts: a way to achieve it would be to pass relax a modulo size & index (modulo size would be the same for all processes, while index would be 0..modulo_size-1), and it would only start connections for teams matching (something % modulo_size == index). The "something" bit could either be a client-fixed auto-incremented id (from the database record) which would be stored alongside the team slack reference and token in redis, or (if we can find something like this) a transformation that would distribute team references in even fashion (maybe something like the md5 of the team could work? no idea how slack references behaves though, would have to check).

^ a bit of brain dump here :smile:

I have to add a 4th question : during my journey exploring slack connection options (in node / ruby), I noticed most problems seem to be around reliability (connections which drop but do not resume, close events not reliably handled, or even lack of feedback when the library has too many connections with problems).

I'd rather have a building basis that will tell me when something go wrong, rather than me believing that a connection is in good shape when it isn't. 

Would you consider relax reliable when it comes to quality of connection?

Again, thanks for your work and support :-)

**Comment by arunthampi** [comment]
> Would you consider relax reliable when it comes to quality of connection?

Yup, we have support builtin for automatic reconnections (we have heartbeats that detect whether a connection is alive and reconnect if dead). We also handle rate-limiting by Slack, so we use their recommended timeout values to make sure that we reconnect at the right time.

We log these reconnection attempts so if you wanted to be alerted when they happen, I think you can probably use Logstash (or something similar) to alert you when they happen.

> a way to achieve it would be to pass relax a modulo size & index (modulo size would be the same for all processes, while index would be 0..modulo_size-1), and it would only start connections for teams matching (something % modulo_size == index).

Would love to explore this sharding in a separate issue -- like you said so far, the users that are using it in production so far haven't needed sharding but I'm sure we'll need it at some point.

**Comment by arunthampi** [comment]
Closing this for now
