### ISSUE TITLE
Enterprise Grid Support?

### ISSUE THREAD

**Issue by bobics** [zerobotlabs/relax#34]
Does Relax support Enterprise Grid? I think the only change that might not work is:

"Support duplicate message deliveries in shared channels when installed on multiple teams"

per the "RTM" section in the API table: https://api.slack.com/enterprise-grid#what_if_i_do_nothing

**Comment by arunthampi** [comment]
@bobics we use a combination of `channel_id` + `message timestamp` to ensure uniqueness of messages. I haven't tried it out on a grid team yet but based on the documentation it looks like this should work. Please raise a separate issue if you do find problems with an enterprise grid integration.
